// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	dto "github.com/ericjovian/gin-template/dto"
	entity "github.com/ericjovian/gin-template/entity"

	mock "github.com/stretchr/testify/mock"
)

// BookUsecase is an autogenerated mock type for the BookUsecase type
type BookUsecase struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: _a0
func (_m *BookUsecase) CreateBook(_a0 dto.BookRequest) (*dto.BookResponse, error) {
	ret := _m.Called(_a0)

	var r0 *dto.BookResponse
	if rf, ok := ret.Get(0).(func(dto.BookRequest) *dto.BookResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BookResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.BookRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookById provides a mock function with given fields: _a0
func (_m *BookUsecase) GetBookById(_a0 int) (*entity.Book, error) {
	ret := _m.Called(_a0)

	var r0 *entity.Book
	if rf, ok := ret.Get(0).(func(int) *entity.Book); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooks provides a mock function with given fields:
func (_m *BookUsecase) GetBooks() ([]*entity.Book, error) {
	ret := _m.Called()

	var r0 []*entity.Book
	if rf, ok := ret.Get(0).(func() []*entity.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookUsecase creates a new instance of BookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookUsecase(t mockConstructorTestingTNewBookUsecase) *BookUsecase {
	mock := &BookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
